# Git repository location
git_host: "http://dev1.vistronix.com:9080"

# Git repo URLs for OZP projects and dependencies
git_cas_url: "ozp/cas-artifacts.git"
git_demo_auth_url: "ozp/demo-auth-service.git"
git_ozp_backend_url: "ozp/ozp-backend.git"
git_ozp_center_url: "ozp/ozp-center.git"
git_demo_apps_url: "ozp/ozp-demo.git"
git_ozp_webtop_url: "ozp/ozp-webtop.git"
git_ozp_iwc_url: "ozp/ozp-iwc.git"
git_ozp_hud_url: "ozp/ozp-hud.git"
git_ozp_help_url: "ozp/ozp-help.git"
git_django_cas_url: "ozp/django-cas.git"

jenkins_username: "{{ vault_jenkins_username }}"
jenkins_password: "{{ vault_jenkins_password }}"
jenkins_host: "{{ vault_jenkins_host }}"
# if offline is true, don't try to download anything. all files (dependencies,
# ozp source, etc) must be available in the 'files' directory of the
# offline role
offline: false
# this is where files downloaded from the internet (3rd party and ozp source)
#  will be placed
download_dir: "/usr/local/ozp/internet_files"
# for vagrant boxes, this will be something like 4440 (or whatever port you
# are forwarding from your host to guest port 4444). For ci or production
# boxes, it will be the standard 443.
site_port: 4440
# port that gunicorn (for ozp-backend) runs on
api_port: 4433
# port that nginx runs on
frontend_port: 4444
# port that metrics nginx configuration runs on
metrics_port: 4450
# port that gunicorn (demo auth) runs on (not used in production)
auth_port: 8081
# if false, basic auth will be used
pki_login: false
# redis password
redis_password: hF2KLXJhhmhDdZKzsG8edGbECKN9kMn26XKhmNAA
# redis port
redis_port: 6379
