---
# Note: no offline option available for this project
- name: Remove any existing local directory for center
  file:
    path: "{{ download_dir }}/demo-auth-service"
    state: absent
  become: true

  - name: Clean up old files
  file:
      path: "/usr/local/ozp/demo-auth-service"
      state: absent
      become: true

- name: Download source from GitHub tag
  git:
    repo: git://dev1.vistronix.com:9080/ozp/demo-auth-service.git
    dest: "{{ download_dir }}/demo-auth-service"
    accept_hostkey: yes
  become: true

- name: Checkout git branch or tag name
  command: git checkout {{ git_tag_or_branch_name }}
  args:
    chdir: /usr/local/ozp/build/demo-auth-service
  become: true
  become_user: ozp

- name: Move files
  command: mv {{ download_dir }}/demo-auth-service /usr/local/ozp/demo-auth-service
  become: true

- name: Use custom settings.py file
  copy:
    src: settings_demoauth.py
    dest: /usr/local/ozp/demo-auth-service/demoauth/settings.py
    owner: ozp
    mode: 0644
  become: true

# For now this is not needed. Maybe later it will be useful to have separate
# auth config from what is on GitHub
#- name: Copy auth_data.json file
#  copy:
#    src: auth_data.json
#    dest: /usr/local/ozp/demo-auth-service/main/auth_data.json
#    owner: ozp
#    mode: 0644
#  become: true

- name: Copy init.d file
  copy:
    src: gunicorn_demoauth.initd
    dest: /etc/init.d/gunicorn_demoauth
    mode: 0755
  become: true

- name: Redeploy the service
  command: service gunicorn_demoauth redeploy
  become: true

- name: Ensure the service is running (and enable it at boot)
  service: name=gunicorn_demoauth state=started enabled=yes
  become: true
