---
# These tasks will download ozp-webtop from GitHub (a branch or tag name) or
# Jenkins (using a specific build number)

- name: Remove any existing webtop directory
  file:
    path: /usr/local/ozp/frontend/webtop
    state: absent
  become: true

- name: Create the directory for the webtop
  file:
    path: /usr/local/ozp/frontend/webtop
    state: directory
    owner: nginx
  become: true

#################
#     GitHub
#################

- name: Remove any existing local directory for webtop
  when: download_from == "github"
  file:
    path: /usr/local/ozp/build/ozp-webtop
    state: absent
  become: true
  become_user: ozp

- name: Download source from GitHub tag
  when: (download_from == "github" and not offline)
  git:
    repo: git://github.com/ozone-development/ozp-webtop.git
    dest: /usr/local/ozp/build/ozp-webtop
    accept_hostkey: yes
  become: true
  become_user: ozp

- name: Checkout git branch or tag name
  when: (download_from == "github" and git_tag_or_branch_name)
  command: git checkout {{ git_tag_or_branch_name }}
  args:
    chdir: /usr/local/ozp/build/ozp-webtop
  become: true
  become_user: ozp

- name: Install bower and grunt
  when: (download_from == "github" and git_tag_or_branch_name)
  shell:  source /usr/local/node_versions/set_node_version.sh {{ node_version }}; npm install -g bower grunt-cli
  args:
    chdir: /usr/local/ozp/build/ozp-webtop
  become: true

- name: Build, test, and create tarball for webtop release
  when: (download_from == "github" and git_tag_or_branch_name)
  shell: source /usr/local/node_versions/set_node_version.sh {{ node_version }};npm install; npm run bower;npm run build;npm run compile;npm run tarDevDate
  args:
    chdir: /usr/local/ozp/build/ozp-webtop
  become: true
  become_user: ozp

- name: Extact release to nginx dir
  when: (download_from == "github" and git_tag_or_branch_name)
  shell: mv `ls *.tar.gz` webtop.tar.gz; tar xzf webtop.tar.gz; cp -r build/* /usr/local/ozp/frontend/webtop/
  args:
    chdir: /usr/local/ozp/build/ozp-webtop
  become: true

#################
#     Jenkins
#################
- name: Download artifacts from Jenkins
  when: (download_from == "jenkins" and not offline)
  uri:
    url: https://{{ jenkins_host }}/view/OZP/job/{{ jenkins_project}}/{{ jenkins_build_number }}/artifact/*zip*/archive.zip
    dest: "{{ download_dir }}/webtop_jenkins_archive.zip"
    method: GET
    user: "{{ jenkins_username }}"
    password: "{{ jenkins_password }}"
    force_basic_auth: true
    timeout: 30
    status_code: 200
  become: true
  become_user: ozp

- name: Remove any existing "artifact" directory
  when: download_from == "jenkins"
  file:
    path: "{{ download_dir }}/archive"
    state: absent
  become: true
  become_user: ozp

- name: Extract archive from Jenkins (outer zip file)
  when: download_from == "jenkins"
  unarchive:
    src: "{{ download_dir }}/webtop_jenkins_archive.zip"
    dest: "{{ download_dir }}"
    copy: no
  become: true
  become_user: ozp

- name: Rename tar file from Jenkins
  when: download_from == "jenkins"
  shell: mv `ls -1 | grep webtop-dev` webtop.tar.gz
  args:
    chdir: "{{ download_dir }}/archive"
  become: true
  become_user: ozp

- name: Extract archive contents from Jenkins download
  when: download_from == "jenkins"
  unarchive:
    src: "{{ download_dir }}/archive/webtop.tar.gz"
    dest: "{{ download_dir }}"
    copy: no
  become: true
  become_user: ozp

#################
#     Local
#################
- name: Extract archive contents from local tarball
  when: download_from == "local"
  unarchive:
    src: "{{ download_dir }}/webtop.tar.gz"
    dest: "{{ download_dir }}"
    copy: no
  become: true
  become_user: ozp

# At this point we have the webtop files in {{ download_dir }}/build. We
# want to move them to /usr/local/ozp/frontend/webtop and change their owner to the nginx user
#

- name: Move files
  when: (download_from == "jenkins" or download_from == "local")
  shell: mv {{ download_dir }}/build/* /usr/local/ozp/frontend/webtop
  become: true

- name: Change ownership
  when: (download_from == "jenkins" or download_from == "local")
  file:
    path: /usr/local/ozp/frontend/webtop
    owner: nginx
    state: directory
    recurse: true
  become: true
